-- MySQL Script generated by MySQL Workbench
-- Thu Oct 15 17:07:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema devpeeporun
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema devpeeporun
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `devpeeporun` DEFAULT CHARACTER SET utf8 ;
USE `devpeeporun` ;

-- -----------------------------------------------------
-- Table `devpeeporun`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devpeeporun`.`menu` ;

CREATE TABLE IF NOT EXISTS `devpeeporun`.`menu` (
  `idmenu` INT NOT NULL AUTO_INCREMENT,
  `meno` VARCHAR(55) NOT NULL,
  `file_path` VARCHAR(90) NULL,
  PRIMARY KEY (`idmenu`),
  UNIQUE INDEX `meno_UNIQUE` (`meno` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devpeeporun`.`image_cat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devpeeporun`.`image_cat` ;

CREATE TABLE IF NOT EXISTS `devpeeporun`.`image_cat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meno` VARCHAR(45) NOT NULL,
  `icon` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `meno_UNIQUE` (`meno` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devpeeporun`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devpeeporun`.`image` ;

CREATE TABLE IF NOT EXISTS `devpeeporun`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meno` VARCHAR(45) NOT NULL,
  `file_path` VARCHAR(150) NOT NULL,
  `image_cat_id` INT NOT NULL,
  PRIMARY KEY (`id`, `image_cat_id`),
  UNIQUE INDEX `meno_UNIQUE` (`meno` ASC) VISIBLE,
  INDEX `fk_image_image_cat_idx` (`image_cat_id` ASC) VISIBLE,
  CONSTRAINT `fk_image_image_cat`
    FOREIGN KEY (`image_cat_id`)
    REFERENCES `devpeeporun`.`image_cat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devpeeporun`.`supporters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devpeeporun`.`supporters` ;

CREATE TABLE IF NOT EXISTS `devpeeporun`.`supporters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
